name: kas_autocare_user
description: "KAS Autocare for end user"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.4
  dio: ^5.9.0
  get_it: ^8.2.0
  dartz: ^0.10.1
  shimmer: ^3.0.0
  bloc: ^9.0.1
  flutter_bloc: ^9.1.1
  carousel_slider: ^5.1.1
  google_fonts: ^6.3.2
  flutter_screenutil: ^5.9.3
  stylish_bottom_bar: ^1.1.1
  equatable: ^2.0.7
  smart_stepper: ^0.0.7
  syncfusion_flutter_datepicker: ^31.1.19
  table_calendar: ^3.2.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  sentry: ^9.7.0
  flutter_dotenv: ^6.0.0
  sentry_flutter: ^9.7.0
  top_snackbar_flutter: ^3.3.0
  flutter_secure_storage: ^9.2.4
  geolocator: ^14.0.1
  stepper_a: ^1.3.1
  font_awesome_flutter: ^10.9.1
  easy_stepper: ^0.8.5+1
  lottie: ^3.3.1
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  universal_stepper: ^1.0.0+1
  auto_size_text: ^3.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  saver_gallery: ^4.0.1
  device_info_plus: ^12.2.0
  location_picker_flutter_map: ^4.1.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  encrypt: ^5.0.3
  pinput: ^6.0.1
  custom_date_range_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/
